export interface ICard {
  id: string;
  type: ECard;
  image: string;
  group: EGroup;
}

export enum ECard {
  ROOT = "ROOT",
  STEM = "STEM",
  LEAVE = "LEAVE",
  PHOTOPERIOD = "PHOTOPERIOD",
  COLD = "COLD",
  MINERAL_DEFICIENCIES = "MINERAL_DEFICIENCIES",
  DROGHT = "DROGHT",
  WEED = "WEED",
  DEFOLIATORS_BUGS = "DEFOLIATORS_BUGS",
  APHIDS_BUGS = "APHIDS_BUGS",
  NEMATODE = "NEMATODE",
  FUNGUS = "FUNGUS",
  FERTILIZER = "FERTILIZER",
  WATER = "WATER",
  HERBICIDE = "HERBICIDE",
  INSECTICIDE = "INSECTICIDE",
  NEMATICIDE = "NEMATICIDE",
  FUNGICIDE = "FUNGICIDE",
  WILDCARD = "WILDCARD",
  CROP_ROTATION = "CROP_ROTATION",
  DISASTER = "DISASTER",
  RELAXED_SEASON = "RELAXED_SEASON",
  FLOWER = "FLOWER",
  FRUIT = "FRUIT",
}
export enum EGroup {
  VEGETETIVE_ORGAN = "VEGETETIVE_ORGAN",
  INDUCTING_CONDITION = "INDUCTING_CONDITION",
  EXTRES = "EXTRES",
  TREATMENT = "TREATMENT",
  WILDCARD = "WILDCARD",
  SPECIAL = "SPECIAL",
  FLOWER = "FLOWER",
  FRUIT = "FRUIT",
}
